kind: KubeSchedulerConfiguration
apiVersion: kubescheduler.config.k8s.io/v1
profiles:
  - plugins:
      multiPoint:
        enabled:
          - name: wasm
    pluginConfig:
      - name: wasm
        args:
          guestURL: "file://./wasm/nodenumber/main.wasm"